###########################################################
#################### Rubocop Rspec ########################
###########################################################

# You can find all configuration options for rubocop-rspec here: https://docs.rubocop.org/rubocop-rspec/cops.html

RSpec/AnyInstance:
  Enabled: true

RSpec/BeforeAfterAll:
  Enabled: true

RSpec/ContextWording:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true

RSpec/ExampleLength:
  Enabled: true

RSpec/ExpectInHook:
  Enabled: true

RSpec/FilePath:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/MessageChain:
  Enabled: true

RSpec/MessageSpies:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: true

RSpec/NamedSubject:
  Enabled: true

RSpec/NestedGroups:
  Max: 7

RSpec/SubjectStub:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true

RSpec/VoidExpect:
  Enabled: true
